### ISSUE TITLE
警報 alarm PK

### ISSUE THREAD

**Issue by karateboy** [karateboy/TSMC_AQMS#10]
2016-06-02 13:54:31,169 - [ERROR] - from play in play-akka.actor.default-dispatcher-1483 
Cannot invoke the action, eventually got an error: java.sql.BatchUpdateException: 違反 PRIMARY KEY 條件約束 'PK_Alarm'。無法在物件 'dbo.Alarm' 中插入重複的索引鍵。重複的索引鍵值是 (A013, 2016-06-02 13:53:39.5300000, I:T20)。

2016-06-02 13:54:31,192 - [ERROR] - from application in play-akka.actor.default-dispatcher-1483 

! @709n8e5ac - Internal server error, for (PUT) [/AlarmRecord/A013] ->

play.api.Application$$anon$1: Execution exception[[BatchUpdateException: 違反 PRIMARY KEY 條件約束 'PK_Alarm'。無法在物件 'dbo.Alarm' 中插入重複的索引鍵。重複的索引鍵值是 (A013, 2016-06-02 13:53:39.5300000, I:T20)。]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:146) [scala-library-2.11.7.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [play_2.11-2.3.10.jar:2.3.10]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.7.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.11-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.11-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.sql.BatchUpdateException: 違反 PRIMARY KEY 條件約束 'PK_Alarm'。無法在物件 'dbo.Alarm' 中插入重複的索引鍵。重複的索引鍵值是 (A013, 2016-06-02 13:53:39.5300000, I:T20)。
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:1178) ~[sqljdbc41.jar:na]
	at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297) ~[commons-dbcp-1.4.jar:1.4]
	at scalikejdbc.StatementExecutor$$anonfun$executeBatch$1.apply(StatementExecutor.scala:320) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.StatementExecutor$$anonfun$executeBatch$1.apply(StatementExecutor.scala:320) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.StatementExecutor$NakedExecutor.apply(StatementExecutor.scala:18) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLAndTiming$$super$apply(StatementExecutor.scala:306) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.StatementExecutor$LoggingSQLAndTiming$class.apply(StatementExecutor.scala:250) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLIfFailed$$super$apply(StatementExecutor.scala:306) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.StatementExecutor$LoggingSQLIfFailed$class.apply(StatementExecutor.scala:283) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.StatementExecutor$$anon$1.apply(StatementExecutor.scala:306) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.StatementExecutor.executeBatch(StatementExecutor.scala:320) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.DBSession$$anonfun$batch$1.apply(DBSession.scala:504) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.DBSession$$anonfun$batch$1.apply(DBSession.scala:498) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.ActiveSession.scalikejdbc$DBSession$$super$using(DBSession.scala:548) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.DBSession$class.using(DBSession.scala:30) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.ActiveSession.using(DBSession.scala:548) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.DBSession$class.batch(DBSession.scala:498) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.ActiveSession.batch(DBSession.scala:548) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.SQLBatch$$anonfun$4.apply(SQL.scala:445) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.SQLBatch$$anonfun$4.apply(SQL.scala:445) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.SQLBatch.apply(SQL.scala:452) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at models.Alarm2$$anonfun$11.apply(Alarm2.scala:183) ~[classes/:na]
	at models.Alarm2$$anonfun$11.apply(Alarm2.scala:163) ~[classes/:na]
	at scalikejdbc.DBConnection$$anonfun$3.apply(DBConnection.scala:297) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.DBConnection$class.scalikejdbc$DBConnection$$rollbackIfThrowable(DBConnection.scala:274) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.DBConnection$class.localTx(DBConnection.scala:295) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.DB.localTx(DB.scala:60) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at scalikejdbc.DB$.localTx(DB.scala:257) ~[scalikejdbc-core_2.11-2.2.6.jar:2.3.6]
	at models.Alarm2$.insertAlarmSeq(Alarm2.scala:163) ~[classes/:na]
	at controllers.DataLogger$$anonfun$insertAlarmRecord$1$$anonfun$apply$12.apply(DataLogger.scala:250) ~[classes/:na]
	at controllers.DataLogger$$anonfun$insertAlarmRecord$1$$anonfun$apply$12.apply(DataLogger.scala:248) ~[classes/:na]
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:76) ~[play-json_2.11-2.3.10.jar:2.3.10]
	at play.api.libs.json.JsSuccess.fold(JsResult.scala:9) ~[play-json_2.11-2.3.10.jar:2.3.10]
	at controllers.DataLogger$$anonfun$insertAlarmRecord$1.apply(DataLogger.scala:244) ~[classes/:na]
	at controllers.DataLogger$$anonfun$insertAlarmRecord$1.apply(DataLogger.scala:239) ~[classes/:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$.invokeBlock(Action.scala:556) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$.invokeBlock(Action.scala:555) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[play_2.11-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:146) [scala-library-2.11.7.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[play-iteratees_2.11-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[play-iteratees_2.11-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[play-iteratees_2.11-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[play-iteratees_2.11-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[play-iteratees_2.11-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[play-iteratees_2.11-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.7.jar:na]
	... 6 common frames omitted

**Comment by karateboy** [comment]
Fixed by change PK as identity.
