### ISSUE TITLE
警報 錯誤

### ISSUE THREAD

**Issue by karateboy** [karateboy/TSMC_AQMS#9]
2016-06-02 14:39:04,168 - [ERROR] - from application in play-akka.actor.default-dispatcher-1543 

! @709nea7d9 - Internal server error, for (GET) [/AlarmReport/A013/3/2016-06-02/2016-06-02?_=1464849172322] ->

play.api.Application$$anon$1: Execution exception[[NoSuchElementException: No value found for '一氧化氮']]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.10.jar:2.3.10]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.7.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:na]
	at scala.util.Failure.recover(Try.scala:216) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.7.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.11-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.11-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.util.NoSuchElementException: No value found for '一氧化氮'
	at scala.Enumeration.withName(Enumeration.scala:124) ~[scala-library-2.11.7.jar:na]
	at models.Alarm2$.getSrcForDisplay(Alarm2.scala:33) ~[classes/:na]
	at views.html.alarmReport$$anonfun$apply$1.apply(alarmReport.template.scala:46) ~[classes/:na]
	at views.html.alarmReport$$anonfun$apply$1.apply(alarmReport.template.scala:41) ~[classes/:na]
	at scala.collection.immutable.List.map(List.scala:277) ~[scala-library-2.11.7.jar:na]
	at views.html.alarmReport$.apply(alarmReport.template.scala:41) ~[classes/:na]
	at controllers.Query$$anonfun$alarmReport$1.apply(Query.scala:743) ~[classes/:na]
	at controllers.Query$$anonfun$alarmReport$1.apply(Query.scala:734) ~[classes/:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Security$AuthenticatedBuilder$$anonfun$authenticate$1.apply(Security.scala:143) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Security$AuthenticatedBuilder$$anonfun$authenticate$1.apply(Security.scala:142) ~[play_2.11-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at play.api.mvc.Security$AuthenticatedBuilder.authenticate(Security.scala:142) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Security$AuthenticatedBuilder.invokeBlock(Security.scala:136) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Security$AuthenticatedBuilder.invokeBlock(Security.scala:131) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[play_2.11-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) ~[play-iteratees_2.11-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) ~[play-iteratees_2.11-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.7.jar:na]
	... 6 common frames omitted

**Comment by karateboy** [comment]
Fixed
